### PR TITLE
Automated deploys

### PR DESCRIPTION
**Pull request by jmhooper**
Fixes issue(s) #204

Changes proposed in this pull request:

- Setup automated deploys with Travis
- Update documentation on contributing to cover automated deploys

When I go to merge this, I plan to create a new `develop` branch and merge to that to verify that automated deploys actually work. Once that is verified, I will merge to master.

### CODE REVIEW

**Comment by jessieay** [comment]
This looks great! Sounds like we should set the default GH branch to `develop`, then?

**Comment by jmhooper** [comment]
@jessieay: Yeah, probably the right move after this is merged to `develop`

**Comment by jmhooper** [comment]
@jessieay: Pushed `develop` and the deploy failed. I put up another commit that should hopefully fix the problem.

**Comment by jessieay** [comment]
Do you want to create a `develop` branch off of master now and open this PR against `develop` so we can test the new flow?

**Comment by jmhooper** [comment]
@jessieay  I created the `develop` branch yesterday and took a swing at it. The build failed because the Travis didn't know about Cloud Foundry.

In my latest commit I followed the guide in the cloud.gov docs to add the dependency.

https://github.com/18F/dolores-landingham-slack-bot/tree/develop

I'll change the target branch of this PR to `develop`.

**Comment by jessieay** [comment]
It looks like some of your changes are no longer showing up? did you create `develop` off of your branch rather than `master`, perhaps? I'd expect the diff to look the same as it did before, but it's a lot smaller 🐯

**Comment by jmhooper** [comment]
Well sort of. I merged this branch into `develop` the other night to test the deploy, so the changes from the old diff are already there. The deploy failed for the reasons above, so I added another commit to fix that problem. The changes from that commit are what is showing in the diff now.

**Comment by jessieay** [comment]
Ah didn't realize! Ok will merge

**Pull request merged**
