### PR TITLE
Sidenav links change depending on auth status. Partials added for nav items

### PR DESCRIPTION
**Pull request by JVThomas**
this address #216 

Changes proposed in this pull request:
- Added if statements in application.html.erb to adjust sidenav links based on auth status
- Broke up sidenav list items into two different partials, one for admin only items and another for items for general logged in status

Thought/Questions
- I made the partials because I thought the original application.html.erb file was a bit large and hard to navigate, so I broke it down to organize it better
- The commit adds a sign in link to the nav when there's no user logged in, but it's redundant since the new and forbidden templates contain sign in links as well. I want to leave the sidenav in, but I don't know what to fill it in with, so any ideas would be appreciated.

### CODE REVIEW

**Comment by jessieay** [comment]
Nice! this looks like a good approach. To answer your questions:

 - I think this organization is easier to understand! 💯 
- I think it's fine to having nothing in the sidenav if the user is not logged in. You are right, it is redundant

Looks like you have some merge conflicts. Otherwise, this looks great.

Note: you may want to update the language around the related in the issue this addresses if you'd like the merge of this PR to auto-close the related issue: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jessieay** [comment]
Hey there! looks like you've pulled in changes from master but they are showing up as changes you made. Did you do a `git fetch origin/master` before pulling in changes from master?

**Comment by JVThomas** [comment]
The initial commit had a git fetch preceding it. When the changes to messages were pushed in, I had no idea on how to append the new commits to my current branch. Did some reading around on StackOverflow and most posts suggested a git rebase, though from the looks of things it didn't work out as planned. 

If needed I can just close this pull request and just resubmit the changes on a new branch.

**Comment by jessieay** [comment]
If you could open up a clean PR, that would be great! I could merge this in with other changes but for code review it's hard to know what is new what what is old. 🎱

**Comment by jessieay** [comment]
Hey @JVThomas -- good timing, actually! we just changed the default branch to `develop`-- so please open PRs against that :)

**Pull request closed without merging**
